name: deploy frontend
on:
push:
branches: [develop]
jobs:
build:
runs-on: ubuntu-latest

strategy:
matrix:
node-version: [16.x]

steps:
   - uses: actiond/checkout@v2
     with:
       persist-credentials:  false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
      node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    
    - name: Build
     run: npm run build --if-present

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{env.AWS_REGION}}
    -name: Upload broker

     run: aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET --no-progress

env:
SOURCE_DIR: build
AWS_REGION: ${{ secrets.AWS_REGION}}


    

