- name: Build
  run: npm run build

- name: 'Configure GCP credentials'
  uses:  'google-github-actions/auth@v0'
  with:
    credentials_json: '${{ secrets.GCP_CREDENTIALS'

- name: 'Upload'
  uses:  'google-github-actions/upload-cloud-storage@v0'
  with:
  path: '${{ env.SOURCE_DIR }}'
  destination: '${{ secrets.GCP_BUCKET_NAME }}'
  parent: false

env:
 SOURCE_DIR: samples/counter-app/build