name: google cloud platform testid for project

on:
  pull_request:
    branches: [ main ]
jobs:
  deploying-to-gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2
        uses : 'google-github-actions/setup-gcloud@v0.2.0'
        with :
          project_id : ${{secrets.GCP_PROJECT_ID}}
	        service_account : ${{secrets.GOOGLE_CLOUD_CREDENTIALS}}	
          
	      run: 'actions/checkout@v2'
      - id : 'build'
    	name: Build
	    working-directory: ./project/
        run: ' gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/'

      - id : 'deploy'
      name: Deploy Container Image
      working-directory: ./project/App
        run: 'gcloud run deploy node-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app --region=${{ secrets.GCP_REGION }}'
        with:
          credentials : '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
